### ISSUE TITLE
Example simple Clojure server locks up REPL after one use

### ISSUE THREAD

**Issue by oubiwann** [oubiwann/clojang#17]
When the following code is run in the REPL and is asked to stop with a client message, it becomes unresponsive on restart and doesn't seem to see client messages anymore. Furthermore, when the server function is ``^C``ed, subsequent function calls (seemingly *any* function call) locks up the REPL.

I suspect the problem is with the connection object not being properly destroyed when stopping the server ...

Here's the code:

```clojure
(require '[clojure.core.match :refer [match]])

(defn png-png
  []
  (let [init-state 0
        self (node/self :srvr)
        _ (node/publish-port self)
        cnnx (node/accept self)]
    (loop [png-count init-state]
      (match [(conn/receive cnnx)]
        [[:ping caller]] (do (conn/! cnnx caller :pong)
                             (recur (inc png-count)))
        [[:get-count caller]] (do (conn/! cnnx caller png-count)
                                  (recur png-count))
        [[:stop caller]] (do (conn/unlink cnnx caller)
                             (node/unpublish self)
                             :stopped)))))
```

**Comment by yurrriq** [comment]
I've had similar issues before and achieved success using `go-loop` (which I may have written. I can't remember), maintaining a reference to the loop channel, and using a "control channel". I'll try to find my code and adapt it to this use case here, unless you've already got a solution in mind.

**Comment by oubiwann** [comment]
I don't have a solution in mind -- any help would be great!

**Comment by oubiwann** [comment]
Although, keep in mind that I'm not using core.async here -- this is just the threading the JInterface uses when it creates a connection ...

**Comment by yurrriq** [comment]
Are you opposed to using `core.async` for control purposes here?

**Comment by oubiwann** [comment]
I plan on doing another example which uses core.async (no code for that yet -- let me open a ticket for that). This one is just meant to show Erlang comms using only JInterfaces connection, pid, and node objects.

**Comment by yurrriq** [comment]
Messy, not-so-great example:

```clojure
(require '[clojure.core.async :refer [>! >!! <! chan go-loop]])

(defn png-png []
  (let [init  0
        self  (doto (node/self :srvr) (node/publish-port))
        cnnx  (node/accept self)   
        <ctrl (chan)]
    (>!! <ctrl :ok) ; nil means stop looping and non-nil means continue
    (go-loop [png-count init]
      (if-let [ok (<! <ctrl)]
        (do (match [(conn/receive cnnx)]
              [[:ping      caller]] (do (conn/! cnnx caller :pong)
                                        (>! <ctrl ok)
                                        (recur (inc png-count)))
              [[:get-count caller]] (do (conn/! cnnx caller png-count)
                                        (>! <ctrl ok)
                                        (recur png-count))
              [[:stop      caller]] (do (conn/unlink cnnx caller)
                                        (node/unpublish self)
                                        (close! <ctrl)
                                        :stopped)))
        ;; TODO: implementation
        (properly-destroy-connection-object)))
    <control))
```

I'm remembering now that this approach works way better when you put an output channel on `<ctrl` and then `>!` results there and use `(go-loop [] ...)`. So then when you `(close! <ctrl)` the loop stops and gets a chance to clean up after itself properly (`properly-destroy-connection-object` above).

**Comment by yurrriq** [comment]
This can be a nice way to control/kill `loop`s though :confused:.

**Comment by oubiwann** [comment]
Okay, it seems that the issue with the original code has to do with (big surprise) threads. When you construct connections manually like that, you need to control every aspect of the connection: the thread, the open port, the transport, etc. Getting a hold of all those things is actually pretty tricky (cumbersome).

Here's what I ended up doing instead, which closely matches the non-OTP LFE code:

```clj
(defn png-png
  []
  (let [init-state 0
        self (node/new :srvr)
        inbox (mbox/new self :pinger)]
    (loop [png-count init-state]
      (match [(mbox/receive inbox)]
        [[:ping caller]]
          (do (mbox/! inbox caller :pong)
              (recur (inc png-count)))
        [[:get-count caller]]
          (do (mbox/! inbox caller png-count)
              (recur png-count))
        [[:stop caller]]
          (do (mbox/close inbox)
              (node/close self)
              :stopped)))))
```

This is for the "quick-and-dirty" section ... one of the many ways in which you can demonstrate it's fragility is create another connection in the Clojure REPL (e.g., create a node and an mbox) and cause an exception. When re-run, the ``png-png`` function will no longer be responsive.

**Comment by oubiwann** [comment]
Okay, change has been committed and publishing docs now ...

**Comment by yurrriq** [comment]
LGTM
