### ISSUE TITLE
Low-level Wrapper: nodes, peers, and self

### ISSUE THREAD

**Issue by oubiwann** [oubiwann/clojang#6]
### Infrastructure

* [x] Create ``defotp`` macro
* [x] Create ``defotp-protected`` macro

### Protocols

* [x] Create protocol for ``OtpAbstractlNode``
* [x] Create protocol for ``OtpLocalNode``
* [x] Create protocol for ``OtpNode``
* [x] Create protocol for ``OtpMbox``
* [x] Create protocol for ``OtpSelf`` 

### Implementation

*Note that some of these may need special constructors*

* [x] Create ``defotp`` for ``OtpLocalNode``
* [x] Create ``defotp`` for ``OtpNode``
* [x] Create ``defotp`` for ``OtpMbox``
* [x] Create ``defotp`` for ``OtpSelf``
* [x] Create ``defotp`` for ``OtpPeer``

**Comment by yurrriq** [comment]
:tada:
